---
magento_patches_enabled: true
magento_composer_patches_version: "^2.0"
magento_patch_url_prefix: "https://gist.githubusercontent.com/hryvinskyi"
magento_sessionreaper_patch_base: "{{ magento_patch_url_prefix }}/16fbc40f3eb00986d7c9673543961c71/raw/a78c1af0fe5d65ad1bcb53ab4eb228f2fec7c6c7"
magento_file_option_patch_base: "{{ magento_patch_url_prefix }}/5557bd641d8f61005d68202c66cf228e/raw/0e23b1416e8f3a6ebc83f85e88da57a84d3fa99b"
magento_patches:
  - package: "magento/module-customer"
    description: "CVE-2025-54236 SessionReaper fix"
    path: "patches/magento/module-customer/cve-2025-54236-session-reaper.patch"
    url: "{{ magento_sessionreaper_patch_base }}/cve-2025-54236-session-reaper.patch"
  - package: "magento/framework"
    description: "Fix file custom option API processing (mage-os#210)"
    path: "patches/magento/framework/fix-file-custom-option-api.patch"
    url: "{{ magento_file_option_patch_base }}/magento-framework.patch"
  - package: "magento/module-catalog"
    description: "Fix file custom option API processing (mage-os#210)"
    path: "patches/magento/module-catalog/fix-file-custom-option-api.patch"
    url: "{{ magento_file_option_patch_base }}/magento-module-catalog.patch"
  - package: "magento/module-quote"
    description: "Fix file custom option API processing (mage-os#210)"
    path: "patches/magento/module-quote/fix-file-custom-option-api.patch"
    url: "{{ magento_file_option_patch_base }}/magento-module-quote.patch"
  - package: "magento/magento2-base"
    description: "Fix file custom option API processing (mage-os#210)"
    path: "patches/magento/magento2-base/fix-file-custom-option-api.patch"
    url: "{{ magento_file_option_patch_base }}/magento-magento2-base.patch"
