magento_domain: "magento.example.com"
magento_letsencrypt_email: "dev@example.com"
magento_admin_email: "admin@example.com"
magento_admin_user: "admin"
magento_admin_password: "ExampleAdmin1"
magento_db_password: "example database password"
magento_repo_public_key: "example-public-key"
magento_repo_private_key: "example-private-key"
magento_opensearch_initial_admin_password: "ExampleSearch1!"
magento_phpmyadmin_uri_path: "/db-console/"
magento_phpmyadmin_basic_auth_user: "pmaops"
magento_phpmyadmin_basic_auth_password: "ExampleBasicAuth1234"
magento_phpmyadmin_config_storage_database: "phpmyadmin"
magento_phpmyadmin_config_storage_user: "pma"
magento_phpmyadmin_config_storage_password: "ExampleStoragePass1234"
